### ISSUE TITLE
**FEATURE REQUEST**

### ISSUE THREAD

**Issue by aviwad** [rliang/gnome-shell-extension-maximize-to-workspace#4] opened 2017-09-04 03:23 UTC
Expected behavior: if an app is maximised in a workspace, no other app should be able to live in the same workspace, maximised or not. somewhat like macOS

Actual behavior: nothing of the above

It would be nice to have this as an option!

GNOME version: 3.24

**Comment by rliang** [comment] 2017-09-04 03:31
Well, this is all the extension should do. If not, clearly there's a bug happening.

Does the command `journalctl /usr/bin/gnome-shell` output any errors about the extension?

**Comment by rliang** [comment] 2017-09-05 02:30
Probably duplicate of #3

**Closed as completed** 2017-09-05 02:30 UTC

**Comment by aviwad** [comment] 2017-10-01 01:13
What? no. I mean, even when your extension works, I can easily put another window in the same workspace as a maximized window. so i wanted a feature request, that a workspace with a maximized window can not have any other windows on it. I just wanted it to be a little more like macOS
